### ISSUE TITLE
Notebooks Separation  

### ISSUE THREAD

**Issue by NoamBenelli** [alexliberzonlab/mothpy#24]
The results reproduction notebook is not functional outside of the mothpy folder. Some code is required to import from the right files/directories.

**Comment by alexlib** [comment]
It is easy to fix with something like this (see in getting started notebook) 

```
import sys
sys.path.append('../mothpy')
import ...
```

**Comment by alexlib** [comment]
@NoamBenelli see new push - i fixed it. but this notebook fails with another error now - this is for you. 

question - why do we need results_reproduction? isn't it the same as getting_started? please make it clear as the introduction is the same apparently

**Comment by NoamBenelli** [comment]
On my machine it fails on "from mothpy import models"
I'll figure out why.

as for your question - Getting started is an in depth explanation on how our software works.
results reproduction is the shortest explanation one need in order to change the simulation conditions and see results. 
i could chop up the important parts from getting started and add them at the end of results_reproduction, it into an addendum.

**Comment by alexlib** [comment]
It’s updated and works. Check again please 

Sent from Mail for Windows 10

**Comment by NoamBenelli** [comment]
I tried a couple of things but I can't seem to make it work, or understand why there would be a difference between our environments. 
I deleted and re-cloned our depository but it seems we have different conditions. 
At the time we were talking about having the entire notebook in the could, in order to prevent those kinds of situations. Is that something that still an option?

**Comment by alexlib** [comment]
You can do a similar one for the other notebook

**Comment by alexlib** [comment]
@NoamBenelli why do we talk about results_reproduction? see how mothpy_getting_started.ipynb works fine and also in the cloud. 
if you want to redefine "new" functions in the notebook - you lose those in the scripts that you should import and then, of course, you have to define also those functions you are importing from.

**Comment by alexlib** [comment]
@NoamBenelli 

https://mybinder.org/v2/gh/alexliberzonlab/mothpy/master?filepath=notebooks%2Fresults_reproduction.ipynb

**Comment by NoamBenelli** [comment]
A. results_reproduction doesn't show graphs. I tried getting it to work for a while but I'm not sure what the problem is. getting_started seems to work better and is more informative so we can throw results_reproduction away. 

B. Getting started isn't perfect .
![image](https://user-images.githubusercontent.com/33618293/57842537-694e7680-77d5-11e9-822b-f0823f759639.png)
I'll get on it, but want this issue to be documented here. 

C. regarding robustness: see image above - notice how D performs well in 0.0001 and 0.0003, but not in 0.0002? I think it (feel free to tell me that I'm entirely mistaken) that implies a strong random factor in the results.

**Comment by alexlib** [comment]
A. Removed the notebook
B. i don't understand what is "not perfect" 
C. I think it's not enough statistics. Please tell me how much do we need to run and I'll setup a PC in the office which is quite strong and it will crunch the jobs through the weekend to get enough statistics.

**Comment by NoamBenelli** [comment]
B. The notation on the x axis came out unaesthetic. It only happens on the binder version, so it's gonna be a bit of a hussle to fix. If you see me pushing a lot of commits in a row today or tomorrow it's probably about that. 

C. Ok, I'll branch off a computationally heavy analysis and will notify here when it's ready.

**Comment by NoamBenelli** [comment]
See new branch of mothpy, "heavy".
Please run compare_navigatores and push the job and data files created.

**Comment by alexlib** [comment]
and then?

**Comment by NoamBenelli** [comment]
I'll code something to visualize and run the results by then. 

If the results seem just as random, we know that this is a property of the system. 
If the results seem "cleaner", we know that we need to place more navigators, and it's just a matter of finding out how many.
